-- MySQL Script generated by MySQL Workbench
-- Sun Sep 27 15:45:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Owner Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Owner Information` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Owner Information` (
  `OwnerID` INT GENERATED ALWAYS AS ()  COMMENT 'Unique ID assigned to each new owner',
  `owner name` VARCHAR(45) NOT NULL,
  `pet name` VARCHAR(45) NOT NULL,
  `petID` INT GENERATED ALWAYS AS ()  COMMENT 'unique ID generated for each new pet',
  `contact number` INT NOT NULL COMMENT 'owner phone number',
  `owner address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OwnerID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `OwnerID_UNIQUE` ON `mydb`.`Owner Information` (`OwnerID` ASC) VISIBLE;

CREATE UNIQUE INDEX `petID_UNIQUE` ON `mydb`.`Owner Information` (`petID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`vaccination history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vaccination history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vaccination history` (
  `petID` INT NOT NULL,
  `dhpp date` DATE NULL,
  `lepto date` DATE NULL,
  `bordetella date` DATE NULL,
  `rabies date` DATE NULL,
  `lyme date` DATE NULL,
  `giardia date` DATE NULL,
  `fecal date` DATE NULL,
  `heartworm test date` DATE NULL,
  `vaccination comment` DATE NULL,
  PRIMARY KEY (`petID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `petID_UNIQUE` ON `mydb`.`vaccination history` (`petID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pet Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pet Information` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pet Information` (
  `petID` INT NOT NULL COMMENT 'primary key inherited from owner information table',
  `owner name` VARCHAR(45) NOT NULL,
  `breed` VARCHAR(45) NULL,
  `color markings` VARCHAR(45) NULL,
  `birthday` INT NULL,
  `gender` VARCHAR(45) NULL,
  `nuetered spayed` TINYINT NULL,
  `allergy type` VARCHAR(45) NULL,
  `allergy comments` VARCHAR(45) NULL,
  `heartwarm current` TINYINT NULL,
  `heartworm type` VARCHAR(45) NULL,
  `percent time outside` INT NULL,
  `diet comments` VARCHAR(45) NULL,
  `client signature` TINYINT NULL,
  `Owner Information_OwnerID` INT NOT NULL,
  `vacinnation history_petID` INT NULL,
  PRIMARY KEY (`petID`, `vacinnation history_petID`),
  CONSTRAINT `fk_Pet Information_Owner Information`
    FOREIGN KEY (`Owner Information_OwnerID`)
    REFERENCES `mydb`.`Owner Information` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pet Information_vacinnation history1`
    FOREIGN KEY (`vacinnation history_petID`)
    REFERENCES `mydb`.`vaccination history` (`petID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `petID_UNIQUE` ON `mydb`.`Pet Information` (`petID` ASC) VISIBLE;

CREATE INDEX `fk_Pet Information_Owner Information_idx` ON `mydb`.`Pet Information` (`Owner Information_OwnerID` ASC) VISIBLE;

CREATE INDEX `fk_Pet Information_vacinnation history1_idx` ON `mydb`.`Pet Information` (`vacinnation history_petID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`medical history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medical history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medical history` (
  `petID` INT NOT NULL,
  `prev date` DATE NULL,
  `prev weight` INT NULL,
  `prev temperature` INT NULL,
  `prev blood pressure` VARCHAR(45) NULL,
  `prev pulse` VARCHAR(45) NULL,
  `prev resperation` VARCHAR(45) NULL,
  `prev pain` VARCHAR(45) NULL,
  `prev vet initials` VARCHAR(45) NULL,
  `prev vaccine date` VARCHAR(45) NULL,
  `prev vaccine type` VARCHAR(45) NULL,
  `prev vaccine next due` DATE NULL,
  `prev vaccine details` VARCHAR(45) NULL,
  `surgical history date` DATE NULL,
  `surgical history procedure` VARCHAR(45) NULL,
  `surgical history details` VARCHAR(45) NULL,
  `Pet Information_petID` INT NOT NULL,
  PRIMARY KEY (`petID`, `Pet Information_petID`),
  CONSTRAINT `fk_medical history_Pet Information1`
    FOREIGN KEY (`Pet Information_petID`)
    REFERENCES `mydb`.`Pet Information` (`petID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idmedical history_UNIQUE` ON `mydb`.`medical history` (`petID` ASC) VISIBLE;

CREATE INDEX `fk_medical history_Pet Information1_idx` ON `mydb`.`medical history` (`Pet Information_petID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
